tabela-quic-vs-ns-quic.pdf: tabela-quic-vs-ns-quic.tex
	pdflatex tabela-quic-vs-ns-quic.tex
	rm *.aux *.log
	xdg-open tabela-quic-vs-ns-quic.pdf

a-QUIC-implementation-for-ns3.pdf: a-QUIC-implementation-for-ns3.tex
	pdflatex a-QUIC-implementation-for-ns3.tex
	rm *.aux *.log
